
###
POST  http://localhost:32935/odata/v4/service/risk/addItem
Content-Type: application/json

{
    "title": "test",
    "descr": "qwe",
    "quantity": 23
}

###
GET http://localhost:33685/odata/v4/service/risk/getSome()
Content-Type: application/json


###
GET http://localhost:3000